server:
  port: 8003


mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.eden.hao.entity                 # 所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml                       # mapper映射文件
    
spring:
   application:
    name: microservicecloud-dept 
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://192.168.0.107:3306/cloudDB03?useSSL=false&serverTimezone=UTC            # 数据库名称
    username: root
    password: root
    
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      #defaultZone: http://localhost:7001/eureka
       defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/      
  instance:
    instance-id: microservicecloud-dept8003
    prefer-ip-address: true     #访问路径可以显示IP地址    
    
info: 
  app.name: edenHao-microservicecloud
  company.name: https://github.io
  build.artifactId: $project.artifactId$
  build.version: $project.version$
    
      
 
